package ru.ilyaM.player;

public enum Rank {
    SUPER_GRANDMASTERS,
    GRANDMASTERS,
    INTERNATIONAL_MASTERS,
    FIDE_MASTERS,
    FIDE_CANDIDATE_MASTER,
    CANDIDATE_MASTER,
    CLASS_A_CATEGORY_1,
    CLASS_B_CATEGORY_2,
    CLASS_C_CATEGORY_3,
    CLASS_D_CATEGORY_4,
    NOVICES
}
