package enums;

public enum OpeningEnum {
    OPEN_GAME,
    RUY_LOPEZ,
    SCOTCH_GAME,
    ITALIAN_GAME,
    FOUR_KNIGHTS_GAME,
    PETROVS_DEFENCE,
    PHILIDOR_DEFENCE,
    VIENNA_GAME,
    BISHOPS_OPENING,
    KINGS_GAMBIT,
    CENTER_GAME,
    DANISH_GAMBIT
    }
