package enums;

public enum RankEnum {
    SUPER_GRANDMASTERS,
    MOST_GRANDMASTERS,
    MOST_INTERNATIONAL_MASTERS,
    MOST_FIDE_MASTERS,
    FIDE_CANDIDATE_MASTERS,
    CANDIDATE_MASTERS,
    CLASS_A,
    CLASS_B,
    CLASS_C,
    CLASS_D,
    NOVICES
}
